[2023-07-21T10:11:50.857+0000] {processor.py:153} INFO - Started process (PID=555) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:11:50.858+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:11:50.859+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:11:50.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:11:50.933+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:11:50.927+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:11:50.934+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:11:50.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.117 seconds
[2023-07-21T10:12:21.325+0000] {processor.py:153} INFO - Started process (PID=558) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:12:21.326+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:12:21.327+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:12:21.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:12:21.361+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:12:21.357+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:12:21.362+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:12:21.402+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.079 seconds
[2023-07-21T10:12:51.751+0000] {processor.py:153} INFO - Started process (PID=561) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:12:51.752+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:12:51.753+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:12:51.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:12:51.787+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:12:51.784+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:12:51.789+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:12:51.893+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.145 seconds
[2023-07-21T10:13:22.140+0000] {processor.py:153} INFO - Started process (PID=564) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:13:22.141+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:13:22.141+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:13:22.141+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:13:22.175+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:13:22.171+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:13:22.176+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:13:22.211+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.074 seconds
[2023-07-21T10:13:52.433+0000] {processor.py:153} INFO - Started process (PID=567) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:13:52.434+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:13:52.434+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:13:52.434+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:13:52.467+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:13:52.463+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:13:52.468+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:13:52.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.070 seconds
[2023-07-21T10:14:22.827+0000] {processor.py:153} INFO - Started process (PID=570) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:14:22.828+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:14:22.829+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:14:22.829+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:14:22.878+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:14:22.874+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:14:22.879+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:14:22.913+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.092 seconds
[2023-07-21T10:14:53.276+0000] {processor.py:153} INFO - Started process (PID=573) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:14:53.277+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:14:53.277+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:14:53.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:14:53.312+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:14:53.308+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:14:53.313+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:14:53.352+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.078 seconds
[2023-07-21T10:15:23.726+0000] {processor.py:153} INFO - Started process (PID=576) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:15:23.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:15:23.727+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:15:23.727+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:15:23.762+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:15:23.758+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:15:23.763+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:15:23.798+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.074 seconds
[2023-07-21T10:15:54.049+0000] {processor.py:153} INFO - Started process (PID=579) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:15:54.050+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:15:54.051+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:15:54.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:15:54.085+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:15:54.081+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:15:54.086+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:15:54.134+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.087 seconds
[2023-07-21T10:16:24.634+0000] {processor.py:153} INFO - Started process (PID=582) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:16:24.635+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:16:24.635+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:16:24.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:16:24.675+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:16:24.670+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:16:24.676+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:16:24.714+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.083 seconds
[2023-07-21T10:16:55.111+0000] {processor.py:153} INFO - Started process (PID=585) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:16:55.112+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:16:55.113+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:16:55.113+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:16:55.145+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:16:55.142+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:16:55.146+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:16:55.182+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.073 seconds
[2023-07-21T10:17:25.556+0000] {processor.py:153} INFO - Started process (PID=588) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:17:25.557+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:17:25.558+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:17:25.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:17:25.592+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:17:25.587+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:17:25.593+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:17:25.623+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.069 seconds
[2023-07-21T10:17:56.092+0000] {processor.py:153} INFO - Started process (PID=591) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:17:56.092+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:17:56.093+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:17:56.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:17:56.128+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:17:56.124+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:17:56.129+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:17:56.161+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.071 seconds
[2023-07-21T10:18:26.521+0000] {processor.py:153} INFO - Started process (PID=594) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:18:26.521+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:18:26.522+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:18:26.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:18:26.558+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:18:26.554+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:18:26.559+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:18:26.603+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.086 seconds
[2023-07-21T10:18:56.891+0000] {processor.py:153} INFO - Started process (PID=597) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:18:56.892+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:18:56.893+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:18:56.893+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:18:56.927+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:18:56.923+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:18:56.928+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:18:56.964+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.075 seconds
[2023-07-21T10:19:27.331+0000] {processor.py:153} INFO - Started process (PID=600) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:19:27.332+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:19:27.332+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:19:27.332+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:19:27.368+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:19:27.364+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:19:27.370+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:19:27.405+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.077 seconds
[2023-07-21T10:19:57.765+0000] {processor.py:153} INFO - Started process (PID=603) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:19:57.766+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:19:57.766+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:19:57.766+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:19:57.800+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:19:57.796+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:19:57.801+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:19:57.836+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.074 seconds
[2023-07-21T10:20:28.283+0000] {processor.py:153} INFO - Started process (PID=606) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:20:28.283+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:20:28.284+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:20:28.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:20:28.318+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:20:28.314+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:20:28.319+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:20:28.362+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.083 seconds
[2023-07-21T10:20:58.643+0000] {processor.py:153} INFO - Started process (PID=609) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:20:58.644+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:20:58.645+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:20:58.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:20:58.678+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:20:58.674+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:20:58.679+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:20:58.713+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.073 seconds
[2023-07-21T10:21:29.030+0000] {processor.py:153} INFO - Started process (PID=612) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:21:29.030+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:21:29.031+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:21:29.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:21:29.066+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:21:29.060+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:21:29.067+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:21:29.106+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.080 seconds
[2023-07-21T10:21:59.470+0000] {processor.py:153} INFO - Started process (PID=615) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:21:59.471+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:21:59.472+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:21:59.472+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:21:59.508+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:21:59.504+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:21:59.509+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:21:59.546+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.079 seconds
[2023-07-21T10:22:30.085+0000] {processor.py:153} INFO - Started process (PID=618) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:22:30.085+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:22:30.086+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:22:30.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:22:30.119+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:22:30.115+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:22:30.120+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:22:30.161+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.078 seconds
[2023-07-21T10:23:00.570+0000] {processor.py:153} INFO - Started process (PID=621) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:23:00.571+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:23:00.572+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:23:00.572+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:23:00.604+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:23:00.600+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:23:00.605+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:23:00.642+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.074 seconds
[2023-07-21T10:23:31.127+0000] {processor.py:153} INFO - Started process (PID=624) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:23:31.128+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:23:31.129+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:23:31.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:23:31.162+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:23:31.158+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:23:31.163+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:23:31.204+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.080 seconds
[2023-07-21T10:24:01.651+0000] {processor.py:153} INFO - Started process (PID=627) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:24:01.652+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:24:01.653+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:24:01.653+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:24:01.686+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:24:01.682+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:24:01.687+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:24:01.729+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.081 seconds
[2023-07-21T10:24:32.178+0000] {processor.py:153} INFO - Started process (PID=630) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:24:32.179+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:24:32.179+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:24:32.179+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:24:32.213+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:24:32.209+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:24:32.214+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:24:32.248+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.072 seconds
[2023-07-21T10:25:02.495+0000] {processor.py:153} INFO - Started process (PID=633) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:25:02.496+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:25:02.496+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:25:02.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:25:02.531+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:25:02.527+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:25:02.532+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:25:02.568+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.075 seconds
[2023-07-21T10:25:32.969+0000] {processor.py:153} INFO - Started process (PID=636) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:25:32.970+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:25:32.971+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:25:32.971+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:25:33.006+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:25:33.002+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:25:33.008+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:25:33.042+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.075 seconds
[2023-07-21T10:26:03.416+0000] {processor.py:153} INFO - Started process (PID=639) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:26:03.417+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:26:03.418+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:26:03.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:26:03.450+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:26:03.446+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:26:03.451+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:26:03.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.070 seconds
[2023-07-21T10:26:33.805+0000] {processor.py:153} INFO - Started process (PID=642) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:26:33.807+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:26:33.808+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:26:33.808+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:26:33.845+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:26:33.841+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:26:33.846+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:26:33.881+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.078 seconds
[2023-07-21T10:27:04.336+0000] {processor.py:153} INFO - Started process (PID=645) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:27:04.337+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:27:04.338+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:27:04.337+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:27:04.372+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:27:04.368+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:27:04.373+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:27:04.413+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.080 seconds
[2023-07-21T10:27:34.728+0000] {processor.py:153} INFO - Started process (PID=648) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:27:34.729+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:27:34.730+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:27:34.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:27:34.764+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:27:34.760+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:27:34.766+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:27:34.800+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.075 seconds
[2023-07-21T10:28:05.236+0000] {processor.py:153} INFO - Started process (PID=651) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:28:05.236+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:28:05.237+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:28:05.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:28:05.270+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:28:05.266+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:28:05.271+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:28:05.305+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.072 seconds
[2023-07-21T10:28:35.719+0000] {processor.py:153} INFO - Started process (PID=654) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:28:35.719+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:28:35.720+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:28:35.720+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:28:35.753+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:28:35.750+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:28:35.754+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:28:35.789+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.073 seconds
[2023-07-21T10:29:06.220+0000] {processor.py:153} INFO - Started process (PID=657) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:29:06.221+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:29:06.221+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:29:06.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:29:06.255+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:29:06.252+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:29:06.257+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:29:06.297+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.079 seconds
[2023-07-21T10:29:36.686+0000] {processor.py:153} INFO - Started process (PID=660) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:29:36.687+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:29:36.688+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:29:36.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:29:36.721+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:29:36.718+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:29:36.722+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:29:36.756+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.073 seconds
[2023-07-21T10:30:07.146+0000] {processor.py:153} INFO - Started process (PID=663) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:30:07.147+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:30:07.148+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:30:07.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:30:07.180+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:30:07.176+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:30:07.181+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:30:07.215+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.071 seconds
[2023-07-21T10:30:37.705+0000] {processor.py:153} INFO - Started process (PID=666) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:30:37.706+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:30:37.707+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:30:37.706+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:30:37.740+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:30:37.736+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:30:37.741+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:30:37.776+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.074 seconds
[2023-07-21T10:31:08.174+0000] {processor.py:153} INFO - Started process (PID=669) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:31:08.175+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:31:08.176+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:31:08.176+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:31:08.210+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:31:08.205+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:31:08.211+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:31:08.247+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.075 seconds
[2023-07-21T10:31:38.512+0000] {processor.py:153} INFO - Started process (PID=672) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:31:38.513+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:31:38.514+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:31:38.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:31:38.547+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:31:38.543+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:31:38.548+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:31:38.588+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.079 seconds
[2023-07-21T10:32:09.111+0000] {processor.py:153} INFO - Started process (PID=675) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:32:09.112+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:32:09.113+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:32:09.113+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:32:09.147+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:32:09.144+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:32:09.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:32:09.184+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.075 seconds
[2023-07-21T10:32:39.596+0000] {processor.py:153} INFO - Started process (PID=678) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:32:39.597+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:32:39.597+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:32:39.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:32:39.631+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:32:39.628+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:32:39.632+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:32:39.668+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.074 seconds
[2023-07-21T10:33:10.041+0000] {processor.py:153} INFO - Started process (PID=681) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:33:10.042+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:33:10.042+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:33:10.042+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:33:10.079+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:33:10.075+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:33:10.081+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:33:10.125+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.087 seconds
[2023-07-21T10:33:40.401+0000] {processor.py:153} INFO - Started process (PID=684) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:33:40.402+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:33:40.403+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:33:40.403+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:33:40.437+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:33:40.433+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:33:40.438+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:33:40.475+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.077 seconds
[2023-07-21T10:34:10.935+0000] {processor.py:153} INFO - Started process (PID=687) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:34:10.936+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:34:10.936+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:34:10.936+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:34:10.969+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:34:10.966+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:34:10.970+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:34:11.001+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.069 seconds
[2023-07-21T10:34:41.382+0000] {processor.py:153} INFO - Started process (PID=690) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:34:41.383+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:34:41.383+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:34:41.383+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:34:41.416+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:34:41.412+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:34:41.418+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:34:41.449+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.070 seconds
[2023-07-21T10:35:11.931+0000] {processor.py:153} INFO - Started process (PID=693) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:35:11.931+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:35:11.933+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:35:11.932+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:35:11.966+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:35:11.963+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:35:11.968+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:35:12.002+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.074 seconds
[2023-07-21T10:35:42.422+0000] {processor.py:153} INFO - Started process (PID=696) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:35:42.423+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:35:42.424+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:35:42.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:35:42.458+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:35:42.454+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:35:42.459+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:35:42.493+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.074 seconds
[2023-07-21T10:36:12.912+0000] {processor.py:153} INFO - Started process (PID=699) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:36:12.913+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:36:12.914+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:36:12.914+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:36:12.948+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:36:12.944+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:36:12.949+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:36:12.989+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.079 seconds
[2023-07-21T10:36:43.385+0000] {processor.py:153} INFO - Started process (PID=702) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:36:43.386+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:36:43.386+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:36:43.386+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:36:43.421+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:36:43.418+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:36:43.422+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:36:43.458+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.076 seconds
[2023-07-21T10:37:13.972+0000] {processor.py:153} INFO - Started process (PID=705) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:37:13.973+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:37:13.974+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:37:13.974+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:37:14.007+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:37:14.003+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:37:14.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:37:14.047+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.077 seconds
[2023-07-21T10:37:44.444+0000] {processor.py:153} INFO - Started process (PID=708) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:37:44.445+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:37:44.446+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:37:44.445+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:37:44.477+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:37:44.473+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:37:44.478+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:37:44.514+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.072 seconds
[2023-07-21T10:38:14.901+0000] {processor.py:153} INFO - Started process (PID=711) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:38:14.901+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:38:14.902+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:38:14.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:38:14.935+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:38:14.931+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:38:14.936+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:38:14.977+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.079 seconds
[2023-07-21T10:38:45.328+0000] {processor.py:153} INFO - Started process (PID=714) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:38:45.329+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:38:45.330+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:38:45.329+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:38:45.364+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:38:45.359+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:38:45.365+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:38:45.406+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.081 seconds
[2023-07-21T10:39:15.883+0000] {processor.py:153} INFO - Started process (PID=717) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:39:15.883+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:39:15.884+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:39:15.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:39:15.917+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:39:15.913+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:39:15.918+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:39:15.951+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.071 seconds
[2023-07-21T10:39:46.409+0000] {processor.py:153} INFO - Started process (PID=720) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:39:46.410+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:39:46.411+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:39:46.411+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:39:46.444+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:39:46.440+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:39:46.445+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:39:46.479+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.072 seconds
[2023-07-21T10:40:16.813+0000] {processor.py:153} INFO - Started process (PID=723) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:40:16.814+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:40:16.815+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:40:16.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:40:16.853+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:40:16.850+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:40:16.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:40:16.892+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.083 seconds
[2023-07-21T10:40:47.074+0000] {processor.py:153} INFO - Started process (PID=726) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:40:47.075+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:40:47.076+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:40:47.076+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:40:47.115+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:40:47.112+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:40:47.117+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:40:47.171+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.100 seconds
[2023-07-21T10:41:17.447+0000] {processor.py:153} INFO - Started process (PID=729) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:41:17.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:41:17.449+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:41:17.449+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:41:17.494+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:41:17.491+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:41:17.495+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:41:17.538+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.095 seconds
[2023-07-21T10:41:47.957+0000] {processor.py:153} INFO - Started process (PID=732) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:41:47.959+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:41:47.961+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:41:47.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:41:48.019+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:41:48.015+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:41:48.020+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:41:48.084+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.136 seconds
[2023-07-21T10:42:18.276+0000] {processor.py:153} INFO - Started process (PID=735) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:42:18.278+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:42:18.279+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:42:18.279+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:42:18.327+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:42:18.324+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:42:18.329+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:42:18.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.108 seconds
[2023-07-21T10:42:48.587+0000] {processor.py:153} INFO - Started process (PID=738) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:42:48.591+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:42:48.593+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:42:48.592+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:42:48.650+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:42:48.646+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:42:48.652+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:42:48.694+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.115 seconds
[2023-07-21T10:43:18.992+0000] {processor.py:153} INFO - Started process (PID=741) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:43:18.993+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:43:18.994+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:43:18.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:43:19.038+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:43:19.033+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:43:19.040+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:43:19.085+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.096 seconds
[2023-07-21T10:43:49.416+0000] {processor.py:153} INFO - Started process (PID=744) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:43:49.417+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:43:49.418+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:43:49.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:43:49.517+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:43:49.512+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:43:49.519+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:43:49.612+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.203 seconds
[2023-07-21T10:44:19.843+0000] {processor.py:153} INFO - Started process (PID=747) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:44:19.845+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:44:19.847+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:44:19.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:44:19.906+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:44:19.901+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:44:19.908+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:44:19.962+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.126 seconds
[2023-07-21T10:44:50.553+0000] {processor.py:153} INFO - Started process (PID=750) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:44:50.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:44:50.559+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:44:50.559+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:44:51.454+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:44:51.446+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:44:51.468+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:44:51.875+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 1.440 seconds
[2023-07-21T10:45:22.115+0000] {processor.py:153} INFO - Started process (PID=753) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:45:22.123+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:45:22.124+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:45:22.124+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:45:22.215+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:45:22.212+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:45:22.217+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:45:22.289+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.178 seconds
[2023-07-21T10:45:52.499+0000] {processor.py:153} INFO - Started process (PID=756) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:45:52.500+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:45:52.501+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:45:52.501+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:45:52.543+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:45:52.539+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:45:52.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:45:52.594+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.097 seconds
[2023-07-21T10:46:23.056+0000] {processor.py:153} INFO - Started process (PID=759) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:46:23.057+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:46:23.058+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:46:23.058+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:46:23.133+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:46:23.128+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:46:23.135+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:46:23.200+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.148 seconds
[2023-07-21T10:46:53.451+0000] {processor.py:153} INFO - Started process (PID=762) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:46:53.452+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:46:53.453+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:46:53.453+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:46:53.506+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:46:53.498+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:46:53.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:46:53.573+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.125 seconds
[2023-07-21T10:47:24.224+0000] {processor.py:153} INFO - Started process (PID=765) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:47:24.225+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:47:24.226+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:47:24.226+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:47:24.266+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:47:24.262+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:47:24.267+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:47:24.307+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.086 seconds
[2023-07-21T10:47:54.728+0000] {processor.py:153} INFO - Started process (PID=768) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:47:54.729+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:47:54.730+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:47:54.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:47:54.765+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:47:54.761+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:47:54.766+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:47:54.803+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.078 seconds
[2023-07-21T10:48:34.838+0000] {processor.py:153} INFO - Started process (PID=39) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:48:34.839+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:48:34.840+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:48:34.840+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:48:34.931+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:48:34.927+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:48:34.932+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:48:34.984+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.154 seconds
[2023-07-21T10:49:05.305+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:49:05.306+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:49:05.307+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:49:05.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:49:05.341+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:49:05.337+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:49:05.342+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:49:05.374+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.072 seconds
[2023-07-21T10:49:35.710+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:49:35.711+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:49:35.712+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:49:35.712+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:49:35.745+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:49:35.741+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:49:35.746+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:49:35.777+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.068 seconds
[2023-07-21T10:50:06.153+0000] {processor.py:153} INFO - Started process (PID=48) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:50:06.154+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:50:06.154+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:50:06.154+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:50:06.189+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:50:06.185+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:50:06.190+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:50:06.221+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.071 seconds
[2023-07-21T10:50:36.621+0000] {processor.py:153} INFO - Started process (PID=51) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:50:36.622+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:50:36.622+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:50:36.622+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:50:36.660+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:50:36.657+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:50:36.662+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:50:36.695+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.077 seconds
[2023-07-21T10:51:07.131+0000] {processor.py:153} INFO - Started process (PID=54) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:51:07.132+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:51:07.134+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:51:07.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:51:07.166+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:51:07.162+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:51:07.167+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:51:07.198+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.070 seconds
[2023-07-21T10:51:37.566+0000] {processor.py:153} INFO - Started process (PID=57) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:51:37.567+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:51:37.568+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:51:37.568+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:51:37.602+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:51:37.598+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:51:37.603+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:51:37.636+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.073 seconds
[2023-07-21T10:52:08.084+0000] {processor.py:153} INFO - Started process (PID=60) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:52:08.086+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:52:08.086+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:52:08.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:52:08.120+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:52:08.116+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:52:08.121+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:52:08.152+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.072 seconds
[2023-07-21T10:52:38.589+0000] {processor.py:153} INFO - Started process (PID=63) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:52:38.590+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T10:52:38.591+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:52:38.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:52:38.623+0000] {logging_mixin.py:137} INFO - [2023-07-21T10:52:38.620+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T10:52:38.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T10:52:38.661+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.074 seconds
[2023-07-21T14:08:53.779+0000] {processor.py:153} INFO - Started process (PID=66) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:08:53.784+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T14:08:53.786+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:08:53.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:08:53.964+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:08:53.958+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T14:08:53.966+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:08:54.014+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.247 seconds
[2023-07-21T14:09:24.189+0000] {processor.py:153} INFO - Started process (PID=69) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:09:24.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T14:09:24.191+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:09:24.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:09:24.227+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:09:24.224+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T14:09:24.229+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:09:24.262+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.076 seconds
[2023-07-21T14:09:54.781+0000] {processor.py:153} INFO - Started process (PID=72) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:09:54.782+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T14:09:54.782+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:09:54.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:09:54.833+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:09:54.829+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T14:09:54.835+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:09:54.875+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.097 seconds
[2023-07-21T14:10:25.154+0000] {processor.py:153} INFO - Started process (PID=75) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:10:25.155+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T14:10:25.156+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:10:25.155+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:10:25.193+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:10:25.189+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T14:10:25.194+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:10:25.228+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.077 seconds
[2023-07-21T14:10:56.391+0000] {processor.py:153} INFO - Started process (PID=78) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:10:56.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T14:10:56.394+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:10:56.393+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:10:56.436+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:10:56.433+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T14:10:56.437+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:10:56.479+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.093 seconds
[2023-07-21T14:11:26.939+0000] {processor.py:153} INFO - Started process (PID=81) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:11:26.940+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T14:11:26.941+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:11:26.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:11:26.983+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:11:26.980+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T14:11:26.984+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:11:27.028+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.092 seconds
[2023-07-21T14:11:57.769+0000] {processor.py:153} INFO - Started process (PID=84) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:11:57.770+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T14:11:57.772+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:11:57.771+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:11:57.829+0000] {logging_mixin.py:137} INFO - [2023-07-21T14:11:57.825+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T14:11:57.831+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T14:11:57.874+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.108 seconds
[2023-07-21T16:13:21.033+0000] {processor.py:153} INFO - Started process (PID=39) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:13:21.034+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T16:13:21.035+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:13:21.035+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:13:21.090+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:13:21.085+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T16:13:21.092+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:13:21.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.108 seconds
[2023-07-21T16:13:51.732+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:13:51.733+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T16:13:51.734+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:13:51.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:13:51.779+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:13:51.775+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T16:13:51.781+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:13:51.814+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.086 seconds
[2023-07-21T16:14:22.081+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:14:22.082+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T16:14:22.083+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:14:22.083+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:14:22.117+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:14:22.113+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T16:14:22.118+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:14:22.145+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.068 seconds
[2023-07-21T16:14:52.606+0000] {processor.py:153} INFO - Started process (PID=48) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:14:52.607+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T16:14:52.608+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:14:52.608+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:14:52.657+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:14:52.655+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T16:14:52.658+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:14:52.690+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.090 seconds
[2023-07-21T16:15:23.191+0000] {processor.py:153} INFO - Started process (PID=51) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:15:23.192+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T16:15:23.194+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:15:23.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:15:23.246+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:15:23.241+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-21T16:15:23.248+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:15:23.284+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.096 seconds
[2023-07-21T16:15:24.200+0000] {processor.py:153} INFO - Started process (PID=52) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:15:24.201+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T16:15:24.202+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:15:24.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:15:24.262+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:15:24.259+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 80, in <module>
    creating_forex_rates_table = HiveOperator(
NameError: name 'HiveOperator' is not defined
[2023-07-21T16:15:24.264+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:15:24.307+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.110 seconds
[2023-07-21T16:15:54.542+0000] {processor.py:153} INFO - Started process (PID=55) to work on /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:15:54.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/forex_data_pipeline.py for tasks to queue
[2023-07-21T16:15:54.545+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:15:54.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:15:54.614+0000] {logging_mixin.py:137} INFO - [2023-07-21T16:15:54.610+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_data_pipeline.py", line 80, in <module>
    creating_forex_rates_table = HiveOperator(
NameError: name 'HiveOperator' is not defined
[2023-07-21T16:15:54.615+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_data_pipeline.py
[2023-07-21T16:15:54.662+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/forex_data_pipeline.py took 0.125 seconds
