[2023-08-16T07:03:54.064+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.is_forex_currencies_file_available manual__2023-08-16T07:03:50.203178+00:00 [queued]>
[2023-08-16T07:03:54.075+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.is_forex_currencies_file_available manual__2023-08-16T07:03:50.203178+00:00 [queued]>
[2023-08-16T07:03:54.076+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T07:03:54.076+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-08-16T07:03:54.077+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T07:03:54.090+0000] {taskinstance.py:1300} INFO - Executing <Task(FileSensor): is_forex_currencies_file_available> on 2023-08-16 07:03:50.203178+00:00
[2023-08-16T07:03:54.094+0000] {standard_task_runner.py:55} INFO - Started process 4639 to run task
[2023-08-16T07:03:54.097+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'forex_data_pipeline', 'is_forex_currencies_file_available', 'manual__2023-08-16T07:03:50.203178+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/forex_data_pipeline.py', '--cfg-path', '/tmp/tmpc8fu7lt6']
[2023-08-16T07:03:54.098+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask is_forex_currencies_file_available
[2023-08-16T07:03:54.158+0000] {task_command.py:388} INFO - Running <TaskInstance: forex_data_pipeline.is_forex_currencies_file_available manual__2023-08-16T07:03:50.203178+00:00 [running]> on host 2761a966e4c6
[2023-08-16T07:03:54.221+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@localhost.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=forex_data_pipeline
AIRFLOW_CTX_TASK_ID=is_forex_currencies_file_available
AIRFLOW_CTX_EXECUTION_DATE=2023-08-16T07:03:50.203178+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-16T07:03:50.203178+00:00
[2023-08-16T07:03:54.229+0000] {base.py:73} INFO - Using connection ID 'forex_path' for task execution.
[2023-08-16T07:03:54.229+0000] {filesystem.py:64} INFO - Poking for file user/local/***/dags/files/forex_currencies.csv
[2023-08-16T07:03:59.241+0000] {base.py:73} INFO - Using connection ID 'forex_path' for task execution.
[2023-08-16T07:03:59.242+0000] {filesystem.py:64} INFO - Poking for file user/local/***/dags/files/forex_currencies.csv
[2023-08-16T07:04:04.253+0000] {base.py:73} INFO - Using connection ID 'forex_path' for task execution.
[2023-08-16T07:04:04.254+0000] {filesystem.py:64} INFO - Poking for file user/local/***/dags/files/forex_currencies.csv
[2023-08-16T07:04:09.266+0000] {base.py:73} INFO - Using connection ID 'forex_path' for task execution.
[2023-08-16T07:04:09.267+0000] {filesystem.py:64} INFO - Poking for file user/local/***/dags/files/forex_currencies.csv
[2023-08-16T07:04:14.274+0000] {base.py:73} INFO - Using connection ID 'forex_path' for task execution.
[2023-08-16T07:04:14.275+0000] {filesystem.py:64} INFO - Poking for file user/local/***/dags/files/forex_currencies.csv
[2023-08-16T07:04:14.276+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 215, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 20.05385970000134 seconds exceeds the specified timeout of 20.
[2023-08-16T07:04:14.286+0000] {taskinstance.py:1323} INFO - Immediate failure requested. Marking task as FAILED. dag_id=forex_data_pipeline, task_id=is_forex_currencies_file_available, execution_date=20230816T070350, start_date=20230816T070354, end_date=20230816T070414
[2023-08-16T07:04:14.300+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task is_forex_currencies_file_available (Sensor has timed out; run duration of 20.05385970000134 seconds exceeds the specified timeout of 20.; 4639)
[2023-08-16T07:04:14.308+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-08-16T07:04:14.324+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
