[2023-08-16T07:13:10.057+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.downloading_rates manual__2023-08-16T07:13:05.596615+00:00 [queued]>
[2023-08-16T07:13:10.069+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.downloading_rates manual__2023-08-16T07:13:05.596615+00:00 [queued]>
[2023-08-16T07:13:10.069+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T07:13:10.070+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-08-16T07:13:10.070+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T07:13:10.084+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): downloading_rates> on 2023-08-16 07:13:05.596615+00:00
[2023-08-16T07:13:10.090+0000] {standard_task_runner.py:55} INFO - Started process 5595 to run task
[2023-08-16T07:13:10.093+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'forex_data_pipeline', 'downloading_rates', 'manual__2023-08-16T07:13:05.596615+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/forex_data_pipeline.py', '--cfg-path', '/tmp/tmpw6gxwr88']
[2023-08-16T07:13:10.093+0000] {standard_task_runner.py:83} INFO - Job 40: Subtask downloading_rates
[2023-08-16T07:13:10.157+0000] {task_command.py:388} INFO - Running <TaskInstance: forex_data_pipeline.downloading_rates manual__2023-08-16T07:13:05.596615+00:00 [running]> on host 2761a966e4c6
[2023-08-16T07:13:10.225+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@localhost.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=forex_data_pipeline
AIRFLOW_CTX_TASK_ID=downloading_rates
AIRFLOW_CTX_EXECUTION_DATE=2023-08-16T07:13:05.596615+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-16T07:13:05.596615+00:00
[2023-08-16T07:13:10.228+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/forex_data_pipeline.py", line 16, in download_rates
    reader = csv.DictReader(forex_currencies, delimiter=';')
NameError: name 'csv' is not defined
[2023-08-16T07:13:10.237+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=forex_data_pipeline, task_id=downloading_rates, execution_date=20230816T071305, start_date=20230816T071310, end_date=20230816T071310
[2023-08-16T07:13:10.247+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 40 for task downloading_rates (name 'csv' is not defined; 5595)
[2023-08-16T07:13:10.265+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-08-16T07:13:10.280+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
