[2023-07-24T06:36:23.633+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:36:23.634+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/draft/forex_data_pipeline.py for tasks to queue
[2023-07-24T06:36:23.635+0000] {logging_mixin.py:137} INFO - [2023-07-24T06:36:23.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:36:23.698+0000] {logging_mixin.py:137} INFO - [2023-07-24T06:36:23.694+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/draft/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/draft/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-24T06:36:23.699+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:36:23.740+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/draft/forex_data_pipeline.py took 0.110 seconds
[2023-07-24T06:36:53.948+0000] {processor.py:153} INFO - Started process (PID=44) to work on /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:36:53.949+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/draft/forex_data_pipeline.py for tasks to queue
[2023-07-24T06:36:53.950+0000] {logging_mixin.py:137} INFO - [2023-07-24T06:36:53.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:36:53.994+0000] {logging_mixin.py:137} INFO - [2023-07-24T06:36:53.989+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/draft/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/draft/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-24T06:36:53.996+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:36:54.038+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/draft/forex_data_pipeline.py took 0.094 seconds
[2023-07-24T06:37:24.137+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:37:24.138+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/draft/forex_data_pipeline.py for tasks to queue
[2023-07-24T06:37:24.138+0000] {logging_mixin.py:137} INFO - [2023-07-24T06:37:24.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:37:24.182+0000] {logging_mixin.py:137} INFO - [2023-07-24T06:37:24.177+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/draft/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/draft/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-24T06:37:24.184+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:37:24.225+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/draft/forex_data_pipeline.py took 0.092 seconds
[2023-07-24T06:37:54.408+0000] {processor.py:153} INFO - Started process (PID=46) to work on /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:37:54.409+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/draft/forex_data_pipeline.py for tasks to queue
[2023-07-24T06:37:54.409+0000] {logging_mixin.py:137} INFO - [2023-07-24T06:37:54.409+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:37:54.452+0000] {logging_mixin.py:137} INFO - [2023-07-24T06:37:54.446+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/draft/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/draft/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-24T06:37:54.453+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:37:54.487+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/draft/forex_data_pipeline.py took 0.082 seconds
[2023-07-24T06:38:24.601+0000] {processor.py:153} INFO - Started process (PID=47) to work on /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:38:24.602+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/draft/forex_data_pipeline.py for tasks to queue
[2023-07-24T06:38:24.603+0000] {logging_mixin.py:137} INFO - [2023-07-24T06:38:24.603+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:38:24.642+0000] {logging_mixin.py:137} INFO - [2023-07-24T06:38:24.638+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/draft/forex_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/draft/forex_data_pipeline.py", line 6, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-07-24T06:38:24.643+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/draft/forex_data_pipeline.py
[2023-07-24T06:38:24.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/draft/forex_data_pipeline.py took 0.079 seconds
